#!/bin/bash

BUILD_DIR=build
mkdir -p $BUILD_DIR
cd $BUILD_DIR

CMAKE_BUILD_TYPE=Release
CMAKE_PREFIX_PATH=/work/d35/d35/kubad35/local-libs
AUTO_COMM_INIT=OFF
BUILD_TESTS=ON
PROFILING=OFF
USE_SANITIZER=OFF

# cray/gnu/aocc
PRG_ENV=gnu
CXX=CC

module load PrgEnv-$PRG_ENV
[ $PROFILING == 1 ] && module load forge

cmake .. \
  -DCMAKE_CXX_COMPILER=${CXX} \
  -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
  -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH \
  -DAUTO_COMM_INIT=$AUTO_COMM_INIT \
  -DBUILD_TESTS=$BUILD_TESTS \
  -DMAP=$PROFILING \
  -DFSANITIZE=$USE_SANITIZER \
