#!/bin/bash

# Create build directory. 
: ${BUILD_DIR=build}
mkdir -p $BUILD_DIR

# Copy configuration to build directory. 
cp $0 $BUILD_DIR
cd $BUILD_DIR

CMAKE_EXPORT_COMPILE_COMMANDS=ON
CMAKE_BUILD_TYPE=Release
CMAKE_PREFIX_PATH=/work/d35/d35/kubad35/local-libs
AUTO_COMM_INIT=OFF
CON_METHOD=gemm
BUILD_TESTS=ON
PROFILING=OFF
USE_SANITIZER=OFF

# cray/gnu/aocc
PRG_ENV=gnu
CXX=CC

module load PrgEnv-$PRG_ENV
[ $PROFILING == 1 ] && module load forge

# ofi/ucx
ARM_MAP_LIB=$PRG_ENV/ofi

cmake .. \
  -DCMAKE_CXX_COMPILER=${CXX} \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=$CMAKE_EXPORT_COMPILE_COMMANDS \
  -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
  -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH \
  -DAUTO_COMM_INIT=$AUTO_COMM_INIT \
  -DCON_METHOD=$CON_METHOD \
  -DBUILD_TESTS=$BUILD_TESTS \
  -DARM_MAP=$PROFILING \
  -DARM_MAP_LIB=$ARM_MAP_LIB \
  -DFSANITIZE=$USE_SANITIZER \
